### Práctica 2: Manipulación de datos con Numpy
#### Alumna: López Aguillón Anayansi Xiadani

In [1]:
import numpy as np

In [2]:
arreglo = np.array([0,1,2,3,4,5])

In [3]:
arreglo, type(arreglo)

(array([0, 1, 2, 3, 4, 5]), numpy.ndarray)

In [4]:
notas = [17,24,34,35,36,66]

ar_notas = np.array(notas, dtype=float)

In [5]:
ar_notas,type(ar_notas[0])

(array([17., 24., 34., 35., 36., 66.]), numpy.float64)

In [6]:
ar_notas_todas = np.array(([0,1,2,3,4,5], notas))
ar_notas_todas

array([[ 0,  1,  2,  3,  4,  5],
       [17, 24, 34, 35, 36, 66]])

#### ndim

In [7]:
# Atributo para conocer cuantas dimensiones tiene un array
print(ar_notas_todas.ndim)
print(ar_notas.ndim)

2
1


#### shape

In [8]:
# Atributo para conocer el tamaño de cada dimension de un array
print(ar_notas_todas.shape)
print(ar_notas.shape)

(2, 6)
(6,)


#### Arrays especiales 

In [9]:
#Arreglo con puros 0
arr = np.zeros((2,3), dtype=float) #2 filas, 3 columnas
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#Arreglo con puros 1
arr2 = np.ones((3,4), dtype=float) #3 filas, 4 columnas
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
#Arreglo con una identidad cuadrada
arr3 = np.identity((4), dtype=float) #4 filas y columnas
print(arr3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
#Arreglo con una identidad cuadrada con el metodo eye
arr4 = np.eye((4), dtype=float) #4 filas y columnas
print(arr4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
#Arreglo con una identidad cuadrada
arr5 = np.arange(1,9) #1 a 9 elementos
print(arr5)

[1 2 3 4 5 6 7 8]


#### Operaciones básicas

In [15]:
arreglo1 = np.arange(1,9)
arreglo1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
#modificamos el arreglo para hacerla de 2 dimensiones y 4 columnas
arreglo1.shape = (2,4) 
arreglo1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arreglo1 + arreglo1 #suma

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [19]:
arreglo1 - arreglo1 #resta

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
arreglo1 * arreglo1 #multiplicacion

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [21]:
arreglo1 ** arreglo1 #exponenciacion

array([[       1,        4,       27,      256],
       [    3125,    46656,   823543, 16777216]], dtype=int32)

In [22]:
arreglo1 / arreglo1 #division

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Álgebra lineal
##### Producto de arrays

In [24]:
a = np.array([1,2,3], float)
b = np.array([0,1,1], float)

np.dot(b, a)

5.0

In [25]:
a.dot(b)

5.0

##### Producto de matrices

In [26]:
a = np.array([[5, 2], [4, 8]], float)
b = np.array([[2, 4], [5, 3]], float)

print(a, "\n -----------")
print(b, "\n -----------")

[[5. 2.]
 [4. 8.]] 
 -----------
[[2. 4.]
 [5. 3.]] 
 -----------


In [27]:
np.dot(a, b)

array([[20., 26.],
       [48., 40.]])

In [29]:
a @ b

array([[20., 26.],
       [48., 40.]])

In [33]:
a = np.array([[0, 1, 4], [5, 2, 3], [1, 4, 8]], float)
b = np.array([2, 3, 5], float)

print(b, "\n -----------")
print(a, "\n -----------")

[2. 3. 5.] 
 -----------
[[0. 1. 4.]
 [5. 2. 3.]
 [1. 4. 8.]] 
 -----------


In [31]:
np.dot(a, b)

array([23., 31., 54.])

In [34]:
a @ b

array([23., 31., 54.])

In [35]:
#matriz multiplied
print(np.matmul(a,b))

[23. 31. 54.]


##### Determinante de una matriz

In [36]:
a = np.array([[8, 5], [3, 4]]) # (8*4) - (5*3)
print(a, "\n -----------")
np.linalg.det(a)

[[8 5]
 [3 4]] 
 -----------


17.0

##### Autovalores y autovectores

In [37]:
vals, vecs = np.linalg.eig(a) #devuelve una tupla
print(vals, "\n -----------")
print(vecs, "\n -----------")

[10.35889894  1.64110106] 
 -----------
[[ 0.90440309 -0.61810602]
 [ 0.4266791   0.78609474]] 
 -----------


##### Funciones universales unarias

In [38]:
a = np.array([2, 4, 9], float)

In [39]:
np.sqrt(a) #raiz cuadrada

array([1.41421356, 2.        , 3.        ])

In [40]:
np.exp(a) #exponencial

array([7.38905610e+00, 5.45981500e+01, 8.10308393e+03])

In [41]:
np.log(a) #logaritmo natural

array([0.69314718, 1.38629436, 2.19722458])

In [42]:
np.sin(a) #seno

array([ 0.90929743, -0.7568025 ,  0.41211849])

In [43]:
np.cos(a) #coseno

array([-0.41614684, -0.65364362, -0.91113026])

In [44]:
np.mean(a) #media aritmetica: suma de cada uno de los elemnetos div entre elementos

5.0

In [45]:
np.std(a) #variacion estandar

2.943920288775949

In [46]:
np.var(a) #varianza

8.666666666666666

##### Funciones universales binarias

In [47]:
arr = np.array([5, 36, 17, 18, 9])
arr_2 = np.array([8, 24, 17, 19, 9])

In [48]:
np.add(arr, arr_2) #suma los elementos correspondientes de los arrays

array([13, 60, 34, 37, 18])

In [49]:
np.subtract(arr, arr_2) #resta los elementos

array([-3, 12,  0, -1,  0])

In [50]:
np.multiply(arr, arr_2) #multiplica los elementos

array([ 40, 864, 289, 342,  81])

In [51]:
np.divide(arr, arr_2) #divide los elementos

array([0.625     , 1.5       , 1.        , 0.94736842, 1.        ])

In [52]:
np.array_equal(arr, arr_2) #evalua si son iguales

False

In [53]:
#compara los elemmentos y crea un nuevo array con el valor mas pequeño 
np.fmin(arr, arr_2) 

array([ 5, 24, 17, 18,  9])

In [54]:
#compara los elemmentos y crea un nuevo array con el valor mas grande
np.fmax(arr, arr_2) 

array([ 8, 36, 17, 19,  9])

##### Agregar y quitar valores a un array

In [56]:
#genera un arreglo con incrememto, inicio y final del rango
arr = np.arange(0,20,2)#inicio,final,incremento
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
#genera un arreglo flotante con numeros aleatorios
#rand generara numeros entre 0 y 1
arr_flot = np.random.rand(4,3)#hace el arreglo de 4 filas y 3 columnas
arr_flot

array([[0.18668546, 0.08756634, 0.66343391],
       [0.49244545, 0.99324088, 0.49971349],
       [0.40065648, 0.97323293, 0.71924168],
       [0.83852399, 0.46063384, 0.64294625]])

In [60]:
#genera un arreglo de numeros enteros aleatorios
arr_ent = np.random.randint(10, size=(2,3))
#numeros entre 0 y 10, con arreglo tamaño 2 filas y 3 columnas
arr_ent

array([[1, 3, 4],
       [0, 3, 9]])

In [61]:
#genera un arreglo con todos los valores 6
arr_6 = np.full((3,3),6)#hace el arreglo de 3 filas y 3 columnas
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [62]:
#agrega los valores 
np.append(arr, [12, 13, 14, 15])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 15])

In [63]:
#inserta valores en lugares determinados
np.insert(arr, 2, [42, 34])#inserta los valores en la posicion 2

#devuelve valor unidimensional

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [64]:
#elimina los valores
#elimina la fila en la posicion 1 y eje 0 (horizontal), si el eje es 1 es vertical
np.delete(arr_ent, 1, axis=0)

array([[1, 3, 4]])

##### Transformaciones
###### as type

In [101]:
arr_ent = np.random.randint(100, size=(3,4))#numeros entre 0 y 10, con arreglo tamaño 2 filas y 3 columnas
arr_ent

array([[31, 93, 36, 30],
       [35, 41,  8, 11],
       [69, 72, 19, 90]])

In [102]:
arr_ent.astype(float)#transforma los valores del array a flotantes

array([[31., 93., 36., 30.],
       [35., 41.,  8., 11.],
       [69., 72., 19., 90.]])

###### sort

In [103]:
arr_ent

array([[31, 93, 36, 30],
       [35, 41,  8, 11],
       [69, 72, 19, 90]])

In [104]:
#ordena los valores del array
arr_ent.sort()
arr_ent

array([[30, 31, 36, 93],
       [ 8, 11, 35, 41],
       [19, 69, 72, 90]])

In [105]:
#ordena los valores por eje vertical
arr_ent.sort(axis=0)
arr_ent

array([[ 8, 11, 35, 41],
       [19, 31, 36, 90],
       [30, 69, 72, 93]])

###### reshape

In [106]:
#re orden el arreglo de 3*4 a 4*3
arr_ent = arr_ent.reshape(4,3)
arr_ent

array([[ 8, 11, 35],
       [41, 19, 31],
       [36, 90, 30],
       [69, 72, 93]])

###### flatten

In [107]:
#Crea un array unidemensional del arreglo original
plano_arr = arr_ent.flatten()
print("ORIGINAL\n", arr_ent)
print("FLATTEN\n", plano_arr)

ORIGINAL
 [[ 8 11 35]
 [41 19 31]
 [36 90 30]
 [69 72 93]]
FLATTEN
 [ 8 11 35 41 19 31 36 90 30 69 72 93]


###### to list

In [108]:
#crea una lista a partir de un array
lista_arr = plano_arr.tolist()
print(lista_arr)
type(lista_arr)

[8, 11, 35, 41, 19, 31, 36, 90, 30, 69, 72, 93]


list

###### separar y juntar arrays

In [109]:
#separa la matriz a 4 arreglos
arrays = np.split(arr_ent, 4)
arrays

[array([[ 8, 11, 35]]),
 array([[41, 19, 31]]),
 array([[36, 90, 30]]),
 array([[69, 72, 93]])]

In [113]:
#concatena el arreglo de la fila 1 y despues la 0, ya que el eje es 0
#si el eje es 1 lo hara horizontalmente
np.concatenate((arrays[1], arrays[0]), axis=0)

array([[41, 19, 31],
       [ 8, 11, 35]])

###### matriz transpuesta

In [116]:
#toma la primera fila del array y lo pone como columna
t_arr = arr_ent.T
print(arr_ent)
print("TRANSPUESTA\n", t_arr)

[[ 8 11 35]
 [41 19 31]
 [36 90 30]
 [69 72 93]]
TRANSPUESTA
 [[ 8 41 36 69]
 [11 19 90 72]
 [35 31 30 93]]


##### Indexacion y slicing

In [118]:
#genera un arreglo de 0 a 64 elemntos que este reordenado en una matriz 8*8
indx = np.array(range(64)).reshape((8, 8))
indx

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [120]:
indx[1, 1] #coordenada del elemento 9

9

In [121]:
indx[0:7:2] #selecciona del indice inicialhasta el final en incrememnto

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [128]:
indx[0:7:2,0] #selecciona solo el primer indice de cada fila encontrada

array([ 0, 16, 32, 48])

In [129]:
#selecciona el primer indx y sus primeros 4 elementos de cada fila encontrada
indx[0:7:2,0:4] 

array([[ 0,  1,  2,  3],
       [16, 17, 18, 19],
       [32, 33, 34, 35],
       [48, 49, 50, 51]])

In [122]:
indx[1, 3:] #elementos de la fila 1 columna 3 en adelante

array([11, 12, 13, 14, 15])

In [123]:
#trae las filas antes de la primera "," y sus columnas despues
#1,3    3,6   5,7
indx[[1, 3, 5], [3, 6, 7]] 

array([11, 30, 47])

In [124]:
#trae todos los elementos de los indx 1,3,5 de 3 en 3
indx[[1, 3, 5], ::3]

array([[ 8, 11, 14],
       [24, 27, 30],
       [40, 43, 46]])

##### Indexacion booleana

In [125]:
data = np.arange(8)
data

array([0, 1, 2, 3, 4, 5, 6, 7])

In [126]:
data < 4 #evalua que los elementos sean menor a 4

array([ True,  True,  True,  True, False, False, False, False])

In [127]:
data[data<4]#hace un arreglo que contenga los elementos menores a 4

array([0, 1, 2, 3])

In [130]:
data[np.array([True, True, True, True, False, False, False, False])]

array([0, 1, 2, 3])

In [131]:
amigos = np.array(['giulia', 'victor', 'joe', 'andrea', 'valeria', 'alberto', 'roque'])

In [132]:
#pregunta si giulia esta dentro de el arroeglo amigos
'giulia' in amigos

True

In [133]:
#devuelve valores donde sea diferentes a la cadena giulia
amigos[amigos!='giulia']

array(['victor', 'joe', 'andrea', 'valeria', 'alberto', 'roque'],
      dtype='<U7')